# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ndpsdaq/online/cens/rootana/kobra

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ndpsdaq/online/cens/rootana/kobra

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ndpsdaq/online/cens/rootana/kobra/CMakeFiles /home/ndpsdaq/online/cens/rootana/kobra/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ndpsdaq/online/cens/rootana/kobra/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ana

# Build rule for target.
ana: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ana
.PHONY : ana

# fast build rule for target.
ana/fast:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/build
.PHONY : ana/fast

#=============================================================================
# Target rules for targets named KoBRA_Dict

# Build rule for target.
KoBRA_Dict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KoBRA_Dict
.PHONY : KoBRA_Dict

# fast build rule for target.
KoBRA_Dict/fast:
	$(MAKE) -f CMakeFiles/KoBRA_Dict.dir/build.make CMakeFiles/KoBRA_Dict.dir/build
.PHONY : KoBRA_Dict/fast

KoBRA_Dict.o: KoBRA_Dict.cxx.o

.PHONY : KoBRA_Dict.o

# target to build an object file
KoBRA_Dict.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/KoBRA_Dict.cxx.o
.PHONY : KoBRA_Dict.cxx.o

KoBRA_Dict.i: KoBRA_Dict.cxx.i

.PHONY : KoBRA_Dict.i

# target to preprocess a source file
KoBRA_Dict.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/KoBRA_Dict.cxx.i
.PHONY : KoBRA_Dict.cxx.i

KoBRA_Dict.s: KoBRA_Dict.cxx.s

.PHONY : KoBRA_Dict.s

# target to generate assembly for a file
KoBRA_Dict.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/KoBRA_Dict.cxx.s
.PHONY : KoBRA_Dict.cxx.s

TAnaManager.o: TAnaManager.cxx.o

.PHONY : TAnaManager.o

# target to build an object file
TAnaManager.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TAnaManager.cxx.o
.PHONY : TAnaManager.cxx.o

TAnaManager.i: TAnaManager.cxx.i

.PHONY : TAnaManager.i

# target to preprocess a source file
TAnaManager.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TAnaManager.cxx.i
.PHONY : TAnaManager.cxx.i

TAnaManager.s: TAnaManager.cxx.s

.PHONY : TAnaManager.s

# target to generate assembly for a file
TAnaManager.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TAnaManager.cxx.s
.PHONY : TAnaManager.cxx.s

TKoBRAADCData.o: TKoBRAADCData.cxx.o

.PHONY : TKoBRAADCData.o

# target to build an object file
TKoBRAADCData.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRAADCData.cxx.o
.PHONY : TKoBRAADCData.cxx.o

TKoBRAADCData.i: TKoBRAADCData.cxx.i

.PHONY : TKoBRAADCData.i

# target to preprocess a source file
TKoBRAADCData.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRAADCData.cxx.i
.PHONY : TKoBRAADCData.cxx.i

TKoBRAADCData.s: TKoBRAADCData.cxx.s

.PHONY : TKoBRAADCData.s

# target to generate assembly for a file
TKoBRAADCData.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRAADCData.cxx.s
.PHONY : TKoBRAADCData.cxx.s

TKoBRAADCHistogram.o: TKoBRAADCHistogram.cxx.o

.PHONY : TKoBRAADCHistogram.o

# target to build an object file
TKoBRAADCHistogram.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRAADCHistogram.cxx.o
.PHONY : TKoBRAADCHistogram.cxx.o

TKoBRAADCHistogram.i: TKoBRAADCHistogram.cxx.i

.PHONY : TKoBRAADCHistogram.i

# target to preprocess a source file
TKoBRAADCHistogram.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRAADCHistogram.cxx.i
.PHONY : TKoBRAADCHistogram.cxx.i

TKoBRAADCHistogram.s: TKoBRAADCHistogram.cxx.s

.PHONY : TKoBRAADCHistogram.s

# target to generate assembly for a file
TKoBRAADCHistogram.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRAADCHistogram.cxx.s
.PHONY : TKoBRAADCHistogram.cxx.s

TKoBRATDCData.o: TKoBRATDCData.cxx.o

.PHONY : TKoBRATDCData.o

# target to build an object file
TKoBRATDCData.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRATDCData.cxx.o
.PHONY : TKoBRATDCData.cxx.o

TKoBRATDCData.i: TKoBRATDCData.cxx.i

.PHONY : TKoBRATDCData.i

# target to preprocess a source file
TKoBRATDCData.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRATDCData.cxx.i
.PHONY : TKoBRATDCData.cxx.i

TKoBRATDCData.s: TKoBRATDCData.cxx.s

.PHONY : TKoBRATDCData.s

# target to generate assembly for a file
TKoBRATDCData.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRATDCData.cxx.s
.PHONY : TKoBRATDCData.cxx.s

TKoBRATDCHistogram.o: TKoBRATDCHistogram.cxx.o

.PHONY : TKoBRATDCHistogram.o

# target to build an object file
TKoBRATDCHistogram.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRATDCHistogram.cxx.o
.PHONY : TKoBRATDCHistogram.cxx.o

TKoBRATDCHistogram.i: TKoBRATDCHistogram.cxx.i

.PHONY : TKoBRATDCHistogram.i

# target to preprocess a source file
TKoBRATDCHistogram.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRATDCHistogram.cxx.i
.PHONY : TKoBRATDCHistogram.cxx.i

TKoBRATDCHistogram.s: TKoBRATDCHistogram.cxx.s

.PHONY : TKoBRATDCHistogram.s

# target to generate assembly for a file
TKoBRATDCHistogram.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TKoBRATDCHistogram.cxx.s
.PHONY : TKoBRATDCHistogram.cxx.s

TPPACAna.o: TPPACAna.cxx.o

.PHONY : TPPACAna.o

# target to build an object file
TPPACAna.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPPACAna.cxx.o
.PHONY : TPPACAna.cxx.o

TPPACAna.i: TPPACAna.cxx.i

.PHONY : TPPACAna.i

# target to preprocess a source file
TPPACAna.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPPACAna.cxx.i
.PHONY : TPPACAna.cxx.i

TPPACAna.s: TPPACAna.cxx.s

.PHONY : TPPACAna.s

# target to generate assembly for a file
TPPACAna.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPPACAna.cxx.s
.PHONY : TPPACAna.cxx.s

TPPACData.o: TPPACData.cxx.o

.PHONY : TPPACData.o

# target to build an object file
TPPACData.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPPACData.cxx.o
.PHONY : TPPACData.cxx.o

TPPACData.i: TPPACData.cxx.i

.PHONY : TPPACData.i

# target to preprocess a source file
TPPACData.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPPACData.cxx.i
.PHONY : TPPACData.cxx.i

TPPACData.s: TPPACData.cxx.s

.PHONY : TPPACData.s

# target to generate assembly for a file
TPPACData.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPPACData.cxx.s
.PHONY : TPPACData.cxx.s

TPlasticAna.o: TPlasticAna.cxx.o

.PHONY : TPlasticAna.o

# target to build an object file
TPlasticAna.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPlasticAna.cxx.o
.PHONY : TPlasticAna.cxx.o

TPlasticAna.i: TPlasticAna.cxx.i

.PHONY : TPlasticAna.i

# target to preprocess a source file
TPlasticAna.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPlasticAna.cxx.i
.PHONY : TPlasticAna.cxx.i

TPlasticAna.s: TPlasticAna.cxx.s

.PHONY : TPlasticAna.s

# target to generate assembly for a file
TPlasticAna.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPlasticAna.cxx.s
.PHONY : TPlasticAna.cxx.s

TPlasticData.o: TPlasticData.cxx.o

.PHONY : TPlasticData.o

# target to build an object file
TPlasticData.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPlasticData.cxx.o
.PHONY : TPlasticData.cxx.o

TPlasticData.i: TPlasticData.cxx.i

.PHONY : TPlasticData.i

# target to preprocess a source file
TPlasticData.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPlasticData.cxx.i
.PHONY : TPlasticData.cxx.i

TPlasticData.s: TPlasticData.cxx.s

.PHONY : TPlasticData.s

# target to generate assembly for a file
TPlasticData.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/TPlasticData.cxx.s
.PHONY : TPlasticData.cxx.s

ana.o: ana.cxx.o

.PHONY : ana.o

# target to build an object file
ana.cxx.o:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/ana.cxx.o
.PHONY : ana.cxx.o

ana.i: ana.cxx.i

.PHONY : ana.i

# target to preprocess a source file
ana.cxx.i:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/ana.cxx.i
.PHONY : ana.cxx.i

ana.s: ana.cxx.s

.PHONY : ana.s

# target to generate assembly for a file
ana.cxx.s:
	$(MAKE) -f CMakeFiles/ana.dir/build.make CMakeFiles/ana.dir/ana.cxx.s
.PHONY : ana.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ana"
	@echo "... KoBRA_Dict"
	@echo "... KoBRA_Dict.o"
	@echo "... KoBRA_Dict.i"
	@echo "... KoBRA_Dict.s"
	@echo "... TAnaManager.o"
	@echo "... TAnaManager.i"
	@echo "... TAnaManager.s"
	@echo "... TKoBRAADCData.o"
	@echo "... TKoBRAADCData.i"
	@echo "... TKoBRAADCData.s"
	@echo "... TKoBRAADCHistogram.o"
	@echo "... TKoBRAADCHistogram.i"
	@echo "... TKoBRAADCHistogram.s"
	@echo "... TKoBRATDCData.o"
	@echo "... TKoBRATDCData.i"
	@echo "... TKoBRATDCData.s"
	@echo "... TKoBRATDCHistogram.o"
	@echo "... TKoBRATDCHistogram.i"
	@echo "... TKoBRATDCHistogram.s"
	@echo "... TPPACAna.o"
	@echo "... TPPACAna.i"
	@echo "... TPPACAna.s"
	@echo "... TPPACData.o"
	@echo "... TPPACData.i"
	@echo "... TPPACData.s"
	@echo "... TPlasticAna.o"
	@echo "... TPlasticAna.i"
	@echo "... TPlasticAna.s"
	@echo "... TPlasticData.o"
	@echo "... TPlasticData.i"
	@echo "... TPlasticData.s"
	@echo "... ana.o"
	@echo "... ana.i"
	@echo "... ana.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

